 1reference
 @rootApi= http://localhost:8003


 @userApi= {{rootApi}}/api/v1/user

 @bookApi={{rootApi}}/api/v1/book


### server testing
GET http://localhost:8003



###  Get user api
POST  {{userApi}}
Content-Type: application/json

{"role":"admin"
   , "fname":"kis",
    "lname":"manandhar",
    "phone":"0449967995",
    "address":"auburn sdyeny",
    "email":"manandharkiran90@gmail.com",
    "password":"12345568t"
}


###  Post  user api
GET {{userApi}}
Content-Type: application/json


### Book api

### fetch all the book
GET {{bookApi}}
Authorization: 


### 
POST {{bookApi}}
Content-Type: application/json

{
    "summary":"kiran",
    "author":"manandhar",
    "year":"2020",
    "title": "how to become javapro",
    "thumnail": "https://m.media-amazon.com/images/I/51wijnc-Y8L.jpg",

}
### Create new burrow record
