 1reference
 @rootApi= http://localhost:8003


 @userApi= {{rootApi}}/api/v1/user


### server testing
GET http://localhost:8003



###  Get user api
POST  {{userApi}}
Content-Type: application/json

{"role":"admin"
   , "fname":"kiran",
    "lname":"manandhar",
    "phone":"0449967997",
    "address":"auburn sdyeny",
    "email":"manandharkiran90@gmail.com",
    "password":"12345568"
}


###  Post  user api
GET {{userApi}}
Content-Type: application/json


### Book api